/*
 * This source file was generated by the Gradle 'init' task
 */
package giallo.zafferano;

import java.io.IOException;
import java.util.ArrayList;

public class App {


    public static void main(String[] args) {
        String resource = "https://www.giallozafferano.it/ricette-cat/Antipasti/";
        Grabber grabber = new Grabber(resource);
        String pageContent = grabber.fetchPageContent();
        ArrayList<Ricetta> ricetteEstratte = new Parser().parseRecipes(pageContent);
        Ricetta ricettaSelezionata = new RecipeLowCalorieSelector().selectRecipe(ricetteEstratte);
        String bodyMail = BodyMailEncoder.createSimpleMessage(ricettaSelezionata);
        MailSender ms = new MailSender( "smtp.gmail.com", 465,"francesco.adriani@franchettisalviani.net", PasswordCointainer.get());
        try {
            ms.sendMail("francesco.adriani@franchettisalviani.net", "Questa è la ricetta ipocalorica in " + resource + ": " + ricettaSelezionata.getTitolo(),bodyMail);
        } catch (IOException | InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
        System.out.println("Email inviata");
    }
}
